/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

import java.awt.Color;
import java.sql.*;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import java.util.concurrent.TimeUnit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
    private KoneksiDatabase dbConnection;
    ResultSet rs = null;
    Statement st = null;
    private PendaftaranAnggota pendaftaranAnggota = null;
            
    public Login() {
        dbConnection = KoneksiDatabase.getInstance();
        initComponents();
        getContentPane().setBackground(new Color(12, 53, 106));
        setSize(423, 364);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputAkun = new javax.swing.JTextField();
        inputPassword = new javax.swing.JPasswordField();
        tombolLogin = new javax.swing.JButton();
        daftarAnggota = new javax.swing.JButton();
        outputLogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Perpustakaan");
        setBackground(new java.awt.Color(158, 130, 95));
        setForeground(new java.awt.Color(158, 130, 95));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(423, 324));
        setMinimumSize(new java.awt.Dimension(423, 324));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 240, 206));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 196, 54));
        jLabel2.setText("Akun            :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 196, 54));
        jLabel3.setText("Password     :");

        inputAkun.setBackground(new java.awt.Color(12, 53, 106));
        inputAkun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputAkun.setForeground(new java.awt.Color(255, 255, 255));
        inputAkun.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        inputAkun.setCaretColor(new java.awt.Color(255, 153, 0));
        inputAkun.setSelectedTextColor(new java.awt.Color(12, 53, 106));
        inputAkun.setSelectionColor(new java.awt.Color(255, 153, 0));
        inputAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAkunActionPerformed(evt);
            }
        });

        inputPassword.setBackground(new java.awt.Color(12, 53, 106));
        inputPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(255, 255, 255));
        inputPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 0)));
        inputPassword.setCaretColor(new java.awt.Color(255, 153, 0));
        inputPassword.setSelectedTextColor(new java.awt.Color(12, 53, 106));
        inputPassword.setSelectionColor(new java.awt.Color(255, 153, 0));
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        tombolLogin.setBackground(new java.awt.Color(153, 176, 128));
        tombolLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        tombolLogin.setText("Login");
        tombolLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLoginActionPerformed(evt);
            }
        });

        daftarAnggota.setBackground(new java.awt.Color(255, 196, 54));
        daftarAnggota.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        daftarAnggota.setForeground(new java.awt.Color(1, 116, 190));
        daftarAnggota.setText("Daftar");
        daftarAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarAnggotaActionPerformed(evt);
            }
        });

        outputLogin.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        outputLogin.setForeground(new java.awt.Color(255, 0, 0));
        outputLogin.setText(" ");

        jButton1.setBackground(new java.awt.Color(1, 116, 190));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(daftarAnggota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tombolLogin)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daftarAnggota)
                    .addComponent(tombolLogin)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAkunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAkunActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void tombolLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLoginActionPerformed
        // TODO add your handling code here:
        try{
            if(this.inputPassword.getText().isBlank() && this.inputAkun.getText().isBlank()){
                this.outputLogin.setText("<html>" + "Mohon input akun dan password!" + "</html>");
            }else if (!this.inputAkun.getText().isBlank() && this.inputPassword.getText().isBlank()) {
                this.outputLogin.setText("<html>" + "Mohon input Password" + "</html>");
            }else if (this.inputAkun.getText().isBlank() && !this.inputPassword.getText().isBlank()) {
                this.outputLogin.setText("<html>" + "Mohon input akun!" + "</html>");
            }else if(this.inputAkun.getText().contains("@admin.ac.id")){
                st = dbConnection.getConnection().createStatement();
                String query = String.format("select akun from data_admin where akun=\"%s\";", this.inputAkun.getText());
                ResultSet rs = st.executeQuery(query);
                if(rs.next() == true){
                    st = dbConnection.getConnection().createStatement();
                    String query10 = String.format("select password from data_admin where akun=\"%s\";", this.inputAkun.getText());
                    ResultSet rs10 = st.executeQuery(query10);
                    if(rs10.next() == true && this.inputPassword.getText().equals(rs10.getString("password"))){
                        this.outputLogin.setText("Berhasil Masuk");
                        dispose();
                        try{
                            TimeUnit.SECONDS.sleep(2);
                        }catch(InterruptedException a){
                            a.printStackTrace();
                        }
                        HomeAdmin home = new HomeAdmin();
                    }else{
                        outputLogin.setForeground(new java.awt.Color(255,0,0));
                        this.outputLogin.setText("<html>"+ "Password salah" + "</html>");
                    }
                }else{
                    outputLogin.setForeground(new java.awt.Color(255,255,255));
                    this.outputLogin.setText("<html>" + "Maaf, akun tersebut tidak tersedia di data admin!" + "</html>");
                }
            }else if(this.inputAkun.getText().contains("@gmail.com")){
                st = dbConnection.getConnection().createStatement();
                String query2 = String.format("select email from data_anggota where email=\"%s\";", this.inputAkun.getText());
                ResultSet rs2 = st.executeQuery(query2);
                if(rs2.next() == true){
                    st = dbConnection.getConnection().createStatement();
                    String query11 = String.format("select nama, nim, alamat, password from data_anggota where email =\"%s\";", this.inputAkun.getText());
                    ResultSet rs11 = st.executeQuery(query11);
                    if(rs11.next() == true && this.inputPassword.getText().equals(rs11.getString("password"))){
                        outputLogin.setForeground(new java.awt.Color(255, 255, 255));
                        this.outputLogin.setText("Berhasil Masuk");
                        dispose();
                        try{
                            TimeUnit.SECONDS.sleep(1);
                        }catch(InterruptedException a){
                            a.printStackTrace();
                        }
                        HomeAnggota ha = new HomeAnggota();
                        ha.anggotaTerpilih(rs11.getString("nama"), rs11.getString("nim"), rs11.getString("alamat"));
                    }else{
                        this.outputLogin.setText("<html>" + "Password salah" + "</html>");
                    }
                }else{
                    outputLogin.setForeground(new java.awt.Color(255,255,255));
                    this.outputLogin.setText("<html>" + "Maaf, akun tersebut tidak tersedia di data anggota! Silahkan membuat akun" + "</html>");
                }
            }else{
                outputLogin.setForeground(new java.awt.Color(22, 103, 196));
                this.outputLogin.setText("<html>" + "Maaf, mohon input akun sesuai format yang telah diberikan!" + "</html>");
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_tombolLoginActionPerformed

    private void daftarAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarAnggotaActionPerformed
        // TODO add your handling code here:
        if (pendaftaranAnggota == null) {
            dispose();
            pendaftaranAnggota = new PendaftaranAnggota();
        }
        pendaftaranAnggota.setVisible(true);
    }//GEN-LAST:event_daftarAnggotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Sampai Jumpa lagi!!");
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarAnggota;
    private javax.swing.JTextField inputAkun;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel outputLogin;
    private javax.swing.JButton tombolLogin;
    // End of variables declaration//GEN-END:variables
}
